
resolver: lts-9.13


packages:
- .
- stock-common
- stock-stats

extra-deps: [yaml-config-0.4.0, stock-common-0.1.0.0, stock-stats-0.1.0.0]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

ghc-options:
  "*": -j -threaded

docker:
  enable: true

image:
  containers:
    -
      base: "fpco/stack-build:lts-9.13"
      name: "peterbecich/stock-collector"

      executables:
        - stock-collector
